### ISSUE TITLE
连接信息编辑

### ISSUE THREAD

**Issue by glennliao** [slowrookie/redis-web-manager#1]
1. 编辑后, 点击确认后会变成新增一条， 而不是修改原来的

![image](https://user-images.githubusercontent.com/14543369/169724317-80c66131-95e2-4ee7-8cac-4130f20271ba.png)
![image](https://user-images.githubusercontent.com/14543369/169724337-71d0899c-2a37-409f-927b-86bf02cc6246.png)
![image](https://user-images.githubusercontent.com/14543369/169724345-e1014659-3e2a-492b-b0fe-10336417880f.png)

2. 删除最后一条时记录仍然显示存在, 但是点击或者再次删除时提示不存在。 刷新后也确实删除了。 估计只是页面上没去除。
![image](https://user-images.githubusercontent.com/14543369/169724466-76685794-c6e3-425a-8cf0-d230af6720c5.png)

**Comment by glennliao** [comment]
使用的版本是 redis-web-manager_2022.5.19-alpha-server.2_windows_amd64

**Comment by slowrookie** [comment]
@glennliao 谢谢你提的`#1`问题,新的构建版本已修复。
