### ISSUE TITLE
是否有key的树状显示和批量删除key的规划

### ISSUE THREAD

**Issue by glennliao** [slowrookie/redis-web-manager#2]
这两点在开发日常中时常会用到， 想问下是否有这两个内容的规划

**Comment by slowrookie** [comment]
@glennliao 很好的问题

1.树状显示之前也思考了很久，由于实现方式不够简洁以及性能问题，目前暂时使用的分组查询代替。或者说灵活使用Key列表上的查询框。 
![image](https://user-images.githubusercontent.com/1582077/169929808-8104b7a8-71ef-4f4b-98b3-d8556e9fd202.png)


2. key的批量删除确实是非常实用的功能，近期会添加该功能。
