### ISSUE TITLE
ssh: tcpChan: deadline not supported

### ISSUE THREAD

**Issue by glennliao** [slowrookie/redis-web-manager#4]
使用ssh通道连接报错,  然后在go-redis [issues/2057](https://github.com/go-redis/redis/issues/2057) 中看到了熟悉的头像发了同样的问题。 所以想问下目前有什么方案可用吗

**Comment by slowrookie** [comment]
谢谢你的提问，这个问题已经修复并接受提交了，但是go-redis的管理者还未发布最新的新版本。
等他们发布新版本后，我这边会第一时间更新。

**Comment by redisviewer** [comment]
作者你好，go-redis发布了最新V9的beta版本，这边发现单机版是可以的，集群还是不行

**Comment by redisviewer** [comment]
> 谢谢你的提问，这个问题已经修复并接受提交了，但是go-redis的管理者还未发布最新的新版本。 等他们发布新版本后，我这边会第一时间更新。

作者不更新一下beta版本吗？

**Comment by slowrookie** [comment]
@travishao 谢谢你的问题，v9的beta我本地也在测试中，目前还不稳定，升级改动影响可能会有点大。所以还在深入了解v9的版本，以便于做出更合理的调整跟改动。
