### ISSUE TITLE
当数据中存在null时，网页报错

### ISSUE THREAD

**Issue by MR5356** [slowrookie/redis-web-manager#5]
报错截图：![image](https://user-images.githubusercontent.com/39437323/172306250-5ee0795c-923e-4f12-92cb-29c91c574a2c.png)
数据示例：![image](https://user-images.githubusercontent.com/39437323/172306294-cb303df9-e192-4c1c-9570-35484762e922.png)

**Comment by slowrookie** [comment]
@MR5356  谢谢你提交的bug，原因应该是 `Stream` 类型值为空时导致的页面显示异常.
