### ISSUE TITLE
docker run bug

### ISSUE THREAD

**Issue by qiushaocloud** [slowrookie/redis-web-manager#8]
使用 docker 镜像运行起来，添加完redis主机后，双击打开就这样了了，界面也白了
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/96336387/212545039-9c023390-88c2-49f0-9fb2-fde97bc602d0.png">

**Comment by FukudaBQ** [comment]
请问是什么原因呀，怎么解决🤦，我这边也有同样的问题

**Comment by slowrookie** [comment]
> 请问是什么原因呀，怎么解决🤦，我这边也有同样的问题

谢谢你的提问，版本兼容愿意导致的。由于工作原因时间不够，该工具许久未维护了。抱歉。

**Comment by FukudaBQ** [comment]
> > 请问是什么原因呀，怎么解决🤦，我这边也有同样的问题
> 
> 谢谢你的提问，版本兼容愿意导致的。由于工作原因时间不够，该工具许久未维护了。抱歉。

感谢感谢
